# Numpy Basics

**By Shaiful Islam**




Numpy is a library for Python that is used for working with arrays. It provides a fast and efficient way to handle large datasets. If you’re using python for data science, either you have used NumPy or must have heard about it. Most of the statistical analysis which needs datato be stored in memory uses Numpy.


### Installation 

```bash
pip install numpy
```



### importing numpy


In [2]:
import numpy as np


### WHY NUMPY?

1. Numpy is faster than Python lists.
2. Numpy arrays are more compact than Python lists.
3. Numpy uses less memory.
4. Numpy is easier to work with.


In [ ]:
## NumPy is meant for creating homogeneous n-dimensional arrays (n = 1..n).
## Unlike Python lists, all elements of a NumPy array should be of same type.
py_arr = [1, 2, "Hello", 3, "World"]  # Python list can have mixed types

# Create NumPy array with homogeneous type
numpy_arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)  # All elements are integers

In [ ]:
import sys
print(sys.getsizeof(py_arr))  # Size of Python list
print(sys.getsizeof(numpy_arr))  # Size of NumPy array

In [ ]:
numpy_arr = np.array([1,2,"Hello",3,"World"], dtype=np.int32) # Error

Numpy advantages compared to Python lists:
1. Uses less memory
2. Provides many built-in functions for array operations
3. Allows specifying data types for optimization
4. Better performance for numerical computations


In [ ]:
import sys

# Create Python list
py_arr = [1, 2, 3, 4, 5, 6]

# Create NumPy array with same values
numpy_arr = np.array([1, 2, 3, 4, 5, 6], dtype=np.int8)

# Calculate memory usage of Python list
sizeof_py_arr = sys.getsizeof(1) * len(py_arr)  # Size = 168

# Calculate memory usage of NumPy array  
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size  # Size = 48

# Print memory usage comparison
print(sizeof_py_arr)
print(sizeof_numpy_arr)

In [ ]:
import numpy as np

py_arr = [1, 2, 3, 4, 5, 6]

# Create NumPy array with same values
numpy_arr = np.array([1, 2, 3, 4, 5, 6], dtype=np.int8)

print(numpy_arr.itemsize * numpy_arr.size)

Optimizing Further

In [ ]:
# For NumPy arrays elements limited to 1 Byte / 8 Bits
numpy_arr = np.array([1, 2, 3, 4, 5, 6], dtype=np.int8)
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size  # Size = 6
print(sizeof_numpy_arr)

# For NumPy arrays elements limited to 2 Bytes / 16 Bits
numpy_arr = np.array([1, 2, 3, 4, 5, 6], dtype=np.int16)
sizeof_numpy_arr = numpy_arr.itemsize * numpy_arr.size  # Size = 12
print(sizeof_numpy_arr)

In [ ]:
size = 1000000
py_list = list(range(size))
py_list

In [18]:
# Let's compare the performance of NumPy arrays vs Python lists
import time
import numpy as np

# Create large Python list and NumPy array
size = 100000000
py_list = list(range(size))
np_array = np.array(range(size))

# Time operation on Python list
start_time = time.time()
py_result = [x * 2 for x in py_list]
py_time = time.time() - start_time

print(py_time)

3.730179786682129


In [20]:
a = np.array([2,4,6])
print(a*2)

[ 4  8 12]


In [19]:

# Time operation on NumPy array 
start_time = time.time()
np_result = np_array * 2
np_time = time.time() - start_time

print(f"Python list time: {py_time:.4f} seconds")
print(f"NumPy array time: {np_time:.4f} seconds")
print(f"NumPy is {py_time/np_time:.1f}x faster")

Python list time: 3.7302 seconds
NumPy array time: 0.1619 seconds
NumPy is 23.0x faster


### Using numpy to create n-dimentional arrays
- An n-dimension array is generally used for creating a matrix or tensors, again mainly for the mathematical calculation purpose.
- Compare to python list base n-dimension arrays, NumPy not only saves the memory usage, it provide a significant number of additional benefits which makes it easy to mathematical calculations


creating a numpy array


In [23]:
ls = [10, 12, 14, 16, 20, 22]
ls_array = np.array(ls)
print(type(ls_array))
type(ls)


<class 'numpy.ndarray'>


list

In [36]:
array_0 = np.ones((5,2,2,4))
print(array_0)



[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [38]:

array_1 = np.ones((6, 3))
print(array_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


How do we know the size of the array?

In [37]:
print(np.shape(array_0))

(5, 2, 2, 4)


The dimensions of the array can be changed at runtime as long as the multiplicity factor produces the same number of elements.
For example, a 2 * 5 matrix can be converted into 5 * 2 and a 1 * 4 into 2 * 2.

In [42]:
ls_array = array_1.reshape((3,3, 2))
print(ls_array)



[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


**NumPy can also generate a predefined set of number for an array.**

The output of this function will always be a single dimension set of numbers. However, we can use reshape on this output to generate dimension of our choice.

In [43]:
np_nd_arr = np.arange(0, 16)
print(np_nd_arr)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [44]:
np_nd_arr = np_nd_arr.reshape((2, 2, 2, 2))
print(np_nd_arr)
np_nd_arr.shape

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


(2, 2, 2, 2)

As reshape(x,y) can convert an array into multi dimensional array, similarly, its possible to create a single dimensional array from any N-D array


In [45]:
f_arr = np_nd_arr.ravel()
print(f_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Slicing an array



In [48]:
np_nd_arr = np.arange(0, 100)
np_nd_arr = np_nd_arr.reshape((10, 10))
print(np_nd_arr.shape)
print(np_nd_arr)
print(np_nd_arr[3:,3:])

(10, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[33 34 35 36 37 38 39]
 [43 44 45 46 47 48 49]
 [53 54 55 56 57 58 59]
 [63 64 65 66 67 68 69]
 [73 74 75 76 77 78 79]
 [83 84 85 86 87 88 89]
 [93 94 95 96 97 98 99]]


### Mathematical operations on NumPy n-Dimension Arrays

- NumPy is not only about efficient storing the data, it also makes it extremely easy to perform mathematical operations on it.

- Any actions on n-dimension arrays behaves exactly similar to mathematical operations.

- NumPy n-dimensional arrays makes it extremely easy to perform mathematical operations on it.

